"use client";
import { useState } from "react";

const PLANOS = [
  { id: "basico", nome: "Básico", detalhe: "3 dias • Alcance local", preco: "R$ 9,90" },
  { id: "recomendado", nome: "Recomendado", detalhe: "7 dias • Alcance regional • Selo verificado", preco: "R$ 19,90" },
  { id: "premium", nome: "Premium", detalhe: "15 dias • Topo das buscas • Suporte", preco: "R$ 34,90" },
];

export function ImpulsionarView() {
  const [plano, setPlano] = useState("recomendado");
  const [pagamento, setPagamento] = useState<"cartao" | "pix">("cartao");
  const atual = PLANOS.find(item => item.id === plano)!;
  return <main className="min-h-[calc(100vh-72px)] bg-[#f7f7ff] px-5 py-9 sm:px-8"><div className="mx-auto max-w-6xl">
    <h1 className="text-2xl font-extrabold text-slate-900">Impulsionar Empréstimo</h1><p className="mt-1 text-sm text-muted">Destaque seu item na comunidade e aumente as chances de empréstimo rapidamente.</p>
    <div className="mt-7 grid gap-6 lg:grid-cols-[1.35fr_.95fr]"><div className="space-y-5">
      <section className="rounded-2xl border border-border bg-white p-5 shadow-sm"><p className="mb-4 text-xs font-bold text-slate-600">ITEM SELECIONADO</p><div className="flex gap-4"><div className="grid h-28 w-32 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-amber-100 to-orange-200 text-5xl shadow-inner">🛠️</div><div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">FERRAMENTAS</span><h2 className="mt-2 text-lg font-extrabold text-slate-900">Furadeira de Impacto Profissional</h2><p className="mt-1 text-sm text-muted">São Paulo, SP • R$ 25/dia</p></div></div></section>
      <section className="rounded-2xl border border-border bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Por que impulsionar?</h2><ul className="mt-4 space-y-3 text-sm text-slate-600"><li className="flex gap-3"><b className="text-primary-600">◉</b><span><strong className="block text-slate-800">Maior visibilidade</strong>Apareça no topo das buscas para usuários da sua região.</span></li><li className="flex gap-3"><b className="text-primary-600">✦</b><span><strong className="block text-slate-800">Empréstimos mais rápidos</strong>Itens impulsionados são alugados até 6x mais rápido.</span></li><li className="flex gap-3"><b className="text-primary-600">♢</b><span><strong className="block text-slate-800">Selo de confiança</strong>Planos superiores incluem selo de destaque no seu card.</span></li></ul></section>
    </div><aside className="rounded-2xl border border-border bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Escolha um Plano</h2><div className="mt-3 space-y-2">{PLANOS.map(item => <button key={item.id} onClick={() => setPlano(item.id)} className={`flex w-full items-center justify-between rounded-xl border p-3 text-left ${plano === item.id ? "border-primary-600 bg-primary-50 ring-1 ring-primary-600" : "border-border hover:border-primary-300"}`}><span><strong className="block text-sm text-slate-900">{item.nome}</strong><small className="text-muted">{item.detalhe}</small></span><strong className="text-sm text-primary-900">{item.preco}</strong></button>)}</div>
      <div className="my-5 border-t border-border" /><h2 className="font-bold text-slate-900">Pagamento</h2><div className="mt-3 grid grid-cols-2 rounded-lg bg-primary-50 p-1"><button onClick={() => setPagamento("cartao")} className={`rounded-md py-2 text-xs font-bold ${pagamento === "cartao" ? "bg-white text-primary-800 shadow-sm" : "text-muted"}`}>▣ Cartão</button><button onClick={() => setPagamento("pix")} className={`rounded-md py-2 text-xs font-bold ${pagamento === "pix" ? "bg-white text-primary-800 shadow-sm" : "text-muted"}`}>⌁ Pix</button></div>
      {pagamento === "cartao" ? <div className="mt-4 space-y-3"><label className="block text-xs font-semibold text-slate-600">Número do Cartão<input className="mt-1 w-full rounded-lg border border-border px-3 py-2.5 font-normal outline-none focus:border-primary-500" placeholder="0000 0000 0000 0000" /></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-600">Validade<input className="mt-1 w-full rounded-lg border border-border px-3 py-2.5 font-normal outline-none focus:border-primary-500" placeholder="MM/AA" /></label><label className="text-xs font-semibold text-slate-600">CVV<input className="mt-1 w-full rounded-lg border border-border px-3 py-2.5 font-normal outline-none focus:border-primary-500" placeholder="123" /></label></div></div> : <div className="mt-4 rounded-xl bg-primary-50 p-4 text-center text-sm text-muted">O QR Code Pix será gerado após a confirmação.</div>}
      <div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="text-sm text-muted">Total</span><strong className="text-xl text-slate-900">{atual.preco}</strong></div><button className="mt-4 w-full rounded-xl bg-primary-900 py-3.5 text-sm font-bold text-white shadow-lg shadow-primary-900/20 hover:bg-primary-700">↗ Confirmar impulsionamento</button><p className="mt-2 text-center text-[10px] text-muted">Pagamento seguro via CicloPay.</p>
    </aside></div>
  </div></main>;
}
